Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,7 +21,7 @@ jobs:
           mkdir test_files
           
           # Create a sample .codemd file for testing
-          echo -e 'This is a test.\n\n```plantuml\nAlice -> Bob: Hello\n```' > test_files/test.codemd
+          echo -e 'This is a test.\n\n```plantuml\nAlice -> Bob: Hello\n```' > test_files/test.src.md
 
       - name: Run Action Locally
         uses: ./  # Points to the root of the action repository
@@ -34,13 +34,13 @@ jobs:
       - name: Verify output
         run: |
           # Check if the output file was created
-          if [ ! -f "test_output/test.src.md" ]; then
+          if [ ! -f "test_output/test.md" ]; then
             echo "Test failed: output file not created."
             exit 1
           fi
 
           # Check the contents of the generated Markdown file
-          grep -q "![Diagram 1]" test_output/test.codemd.src.md || (echo "Test failed: SVG link not found." && exit 1)
+          grep -q "![Diagram 1]" test_output/test.md || (echo "Test failed: SVG link not found." && exit 1)
 
       - name: Clean up
         run: |
